apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-myrep
  namespace: webapp
  labels:
    app: webapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: allenaira/2048:new1
          ports:
            - containerPort: 80
