apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-appdeply
  namespace: webapp
  labels:
    app: webapp-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webapp-deploy
  template:
    metadata:
      labels:
        app: webapp-deploy
    spec:
      containers:
      - name: webapp
        image: allenaira/2048:new1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
